### PR TITLE
feat: Use sorted API requests to support crash tolerant incremental sync 

### PR DESCRIPTION
**Pull request by JichaoS**
The streams changed support sorted responses

Ex: https://developers.klaviyo.com/en/reference/get_campaigns

This PR takes advantage of ascending timestamps to support fault tolerant incremental syncs that picks up at the last left-off place.

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Hi @JichaoS! Thanks for contributing. Can you merge `main` into your branch?

**Comment by JichaoS** [comment]
@edgarrmondragon Updated!

**Comment by JichaoS** [comment]
@edgarrmondragon which API version is the secret pointing to? Can we update that to at min "2023-02-22" (which is what I've been running with)

**Comment by edgarrmondragon** [comment]
@JichaoS It's pointing to revision 2023-10-15, but you probably need to set the secrets in your fork for GH actions to pick them up.

**Comment by JichaoS** [comment]
Thanks, I tested this out locally and it's WAI. Getting same results as meltanolabs/head on my test acct.

**Review by edgarrmondragon — APPROVED** [review]
Thanks @JichaoS

**Pull request merged**
